###
POST http://localhost:3000/admin/create
Content-Type: application/json

{
	"email": "Anitta@hotmail.com",
	"name": "Paulo Juanes",
	"password": "#Pui123433"
}

###
POST http://localhost:3000/customer/create
Content-Type: application/json

{
	"email":"joao@carneiro.com", 
	"name": "Joao Carneiro",
    "cpf": "57664504864"
}

###
POST http://localhost:3000/admin/auth
Content-Type: application/json

{
  "email": "PauloJuanes@hotmail.com",
  "password": "#Pui123433"
}

###
GET  http://localhost:3000/customer/registration 
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5YWRmZTA0LTExNWItNGFlMy05YmNmLTJhZjNhZmI0NjQzMSIsImlhdCI6MTY3NzgwMjQ3MiwiZXhwIjoxNjc3ODA2MDcyfQ.0PMz6_AiXzw61VbH9MHks72UPBAOpPsrEpi5Ra8yk2E
Content-Type: application/json

###
DELETE  http://localhost:3000/customer/delete/300a9eee-a627-4946-9709-8b6a36a49426



